config/routes.rb
Rails.application.routes.draw do

  resources :functions
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :profiles
  resources :events
  resources :menu_options
  resources :rols
  resources :countries
  resources :interactions
  resources :advertising_campaigns
  resources :products
  resources :payments
  get 'welcome/index'

  resources :organizations

  devise_for :users, :controllers => { :registration => "registration", :omniauth_callbacks => "omniauth_callbacks" }
  scope "/admin" do
    resources :users
  end
  get 'functions/sidebar' => 'functions#sidebar'

  devise_scope :user do
     get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
     get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end

   root 'paginas#index'

      get 'paginas/formulario'
      get 'paginas/registroAdministradorOrg'
      get 'paginas/iniciarSesionAdmOrg'
      get 'paginas/registro_org'
      get 'paginas/consultar_org'
      get 'paginas/consultar_detalle_org'
      get 'paginas/modificar_org'
      get 'paginas/opc_administrador_sistema'
      get 'paginas/habilitar_organizacion_administrador'
      get 'paginas/consultar_detalle_adm'
      get 'paginas/registro_pago'
      get 'paginas/consultar_pagos'
      get 'paginas/modificar_datos_admS'
      get 'paginas/registro_ejecutivoS'
      get 'paginas/consultar_ejecutivos'
      get 'paginas/opc_administrador_org'
      get 'paginas/registro_empleados'
      get 'paginas/consultar_ejecutivos_org'
      get 'paginas/consultar_analistas_org'
      get 'paginas/registro_pago_org'
      get 'paginas/consultar_pagos_org'
      get 'paginas/modificar_rol_org'
      get 'paginas/modificar_datos_admOrg'
      get 'paginas/publicar_novedad'
      get 'paginas/cambiar_fondo'
      get 'paginas/opc_ejecutivo_org'
      get 'paginas/publicar_campanna'
      get 'paginas/consultar_campannas'
      get 'paginas/modificar_datos_ejecutivo_org'
      get 'paginas/registro_evento_ejecutivo_org'
      get 'paginas/consultar_novedades'
      get 'paginas/consultar_eventos_ejecutivo'
      get 'paginas/publicar_campanna_sistema'
      get 'paginas/consultar_campannas_sistema'
      get 'paginas/modificar_datos_ejecutivo_sistema'
      get 'paginas/opc_ejecutivo_sistema'
      get 'paginas/opc_analista_org'
      get 'paginas/modificar_datos_analista_org'
      get 'paginas/registro_reporte'
      get 'paginas/consultar_reportes'
      get 'paginas/iniciar_sesion_cliente'
      get 'paginas/registro_cliente'
      get 'paginas/registro_org_administrador_sistema'
      get 'paginas/registro_administradorOrg_admSist'
      get 'paginas/opc_cliente'
      get 'paginas/detalle_estadistica_interes'
      get 'paginas/consultar_detalle_estadistica_intereses'
      get 'paginas/modificar_datos_cliente'
      get 'paginas/cambiar_fondo_cliente'

   get ':controller(/:action(/:id))(.:format)'
   post ':controller(/:action(/:id))(.:format)'
end

app/models/function.rb
class Function < ActiveRecord::Base
  belongs_to :rol
end

app/controllers/functions_controller.rb
class FunctionsController < InheritedResources::Base

  private

    def function_params
      params.require(:function).permit(:name, :info, :url, :father_id, :rol_id)
    end
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/views/functions/_form.html.erb
<%= form_for(@function) do |f| %>
  <% if @function.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@function.errors.count, "error") %> prohibited this function from being saved:</h2>

      <ul>
      <% @function.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :info %><br>
    <%= f.text_field :info %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :father_id %><br>
    <%= f.text_field :father_id %>
  </div>
  <div class="field">
    <%= f.label :rol_id %><br>
    <%= f.text_field :rol_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/functions/_sidebar.html.erb
<ul id="slide-out" class="side-nav">
  <% if user_signed_in? %>
    <ul class="collapsible" data-collapsible="accordion">
      <% if @all_functions.size != 0 %>
        <% @all_functions.each do |function| %>
          <li>
            <% if function.rol_id == current_user.rol_id %>
            <% if function.father_id == '0' %>
              <div class="collapsible-header"><%= function.name %></div>
              <% father = function %>
              <% @all_functions.each do |f| %>
                <% if f.father_id.to_i == father.id %>
                  <div class="collapsible-body"><%= link_to f.name, f.url %></div>
                <% end %>
              <% end %>
            <% end %>
            <% end %>
          </li>
        <% end %>
      <% end %>
    </ul>
  <% else %>
    <h5><i class="info_outline"></i>No esta autorizado para ver el menu</h5>
  <% end %>
</ul>
<a href="#" data-activates="slide-out" class="button-collapse"><i class="small mdi-navigation-menu" style="color: #000;" ></i></a>

app/views/functions/edit.html.erb
<h1>Editing Function</h1>

<%= render 'form' %>

<%= link_to 'Show', @function %> |
<%= link_to 'Back', functions_path %>

app/views/functions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Functions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Info</th>
      <th>Url</th>
      <th>Father</th>
      <th>Rol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @functions.each do |function| %>
      <tr>
        <td><%= function.name %></td>
        <td><%= function.info %></td>
        <td><%= function.url %></td>
        <td><%= function.father_id %></td>
        <td><%= function.rol %></td>
        <td><%= link_to 'Show', function %></td>
        <td><%= link_to 'Edit', edit_function_path(function) %></td>
        <td><%= link_to 'Destroy', function, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Function', new_function_path %>

app/views/functions/new.html.erb
<h1>New Function</h1>

<%= render 'form' %>

<%= link_to 'Back', functions_path %>

app/views/functions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @function.name %>
</p>

<p>
  <strong>Info:</strong>
  <%= @function.info %>
</p>

<p>
  <strong>Url:</strong>
  <%= @function.url %>
</p>

<p>
  <strong>Father:</strong>
  <%= @function.father_id %>
</p>

<p>
  <strong>Rol:</strong>
  <%= @function.rol %>
</p>

<%= link_to 'Edit', edit_function_path(@function) %> |
<%= link_to 'Back', functions_path %>