config/routes.rb
Rails.application.routes.draw do

  resources :functions
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :profiles
  resources :events
  resources :menu_options
  resources :rols
  resources :countries
  resources :interactions
  resources :advertising_campaigns
  resources :products
  resources :payments
  get 'welcome/index'

  resources :organizations

  devise_for :users, :controllers => { :registration => "registration", :omniauth_callbacks => "omniauth_callbacks" }
  scope "/admin" do
    resources :users
  end
  get 'functions/sidebar' => 'functions#sidebar'

  devise_scope :user do
     get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
     get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end

   root 'paginas#index'

      get 'paginas/formulario'
      get 'paginas/registroAdministradorOrg'
      get 'paginas/iniciarSesionAdmOrg'
      get 'paginas/registro_org'
      get 'paginas/consultar_org'
      get 'paginas/consultar_detalle_org'
      get 'paginas/modificar_org'
      get 'paginas/opc_administrador_sistema'
      get 'paginas/habilitar_organizacion_administrador'
      get 'paginas/consultar_detalle_adm'
      get 'paginas/registro_pago'
      get 'paginas/consultar_pagos'
      get 'paginas/modificar_datos_admS'
      get 'paginas/registro_ejecutivoS'
      get 'paginas/consultar_ejecutivos'
      get 'paginas/opc_administrador_org'
      get 'paginas/registro_empleados'
      get 'paginas/consultar_ejecutivos_org'
      get 'paginas/consultar_analistas_org'
      get 'paginas/registro_pago_org'
      get 'paginas/consultar_pagos_org'
      get 'paginas/modificar_rol_org'
      get 'paginas/modificar_datos_admOrg'
      get 'paginas/publicar_novedad'
      get 'paginas/cambiar_fondo'
      get 'paginas/opc_ejecutivo_org'
      get 'paginas/publicar_campanna'
      get 'paginas/consultar_campannas'
      get 'paginas/modificar_datos_ejecutivo_org'
      get 'paginas/registro_evento_ejecutivo_org'
      get 'paginas/consultar_novedades'
      get 'paginas/consultar_eventos_ejecutivo'
      get 'paginas/publicar_campanna_sistema'
      get 'paginas/consultar_campannas_sistema'
      get 'paginas/modificar_datos_ejecutivo_sistema'
      get 'paginas/opc_ejecutivo_sistema'
      get 'paginas/opc_analista_org'
      get 'paginas/modificar_datos_analista_org'
      get 'paginas/registro_reporte'
      get 'paginas/consultar_reportes'
      get 'paginas/iniciar_sesion_cliente'
      get 'paginas/registro_cliente'
      get 'paginas/registro_org_administrador_sistema'
      get 'paginas/registro_administradorOrg_admSist'
      get 'paginas/opc_cliente'
      get 'paginas/detalle_estadistica_interes'
      get 'paginas/consultar_detalle_estadistica_intereses'
      get 'paginas/modificar_datos_cliente'
      get 'paginas/cambiar_fondo_cliente'

   get ':controller(/:action(/:id))(.:format)'
   post ':controller(/:action(/:id))(.:format)'
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
	def index
	end
end

app/views/paginas/consultar_detalle_org.html.erb
<body class="fondoform" xmlns="http://www.w3.org/1999/html">
<div class="container">
  <div class="row">


      <h4 class="black-text center">Detalles de la Organizaci&oacute;n</h4>
    <div class="col s12 fondodiv">

      <div class="input-field col s6">
        <select disabled>
          <option value=""disabled selected>Oro</option>
          <option value="1">Bronce - Gratis</option>
          <option value="2">Plata - 50$</option>
          <option value="3">Oro - 200$</option>
        </select>
        <label>Tipo de plan</label>
      </div>


      <div class="input-field col s6">

        <select disabled>
          <option value="" disabled selected>Servicios</option>
          <option value="1">Producci&oacute;n</option>
          <option value="2">Compra - Venta</option>
          <option value="2">Servicios</option>
          <option value="3">Sin fines de Lucro</option>
        </select>
        <label>Tipo de Organizaci&oacute;n</label>
      </div>

      <div class="input-field col s6 ">
        <i class="material-icons prefix iconnegro">business</i>
        <input disabled value="2549856" id="iFiscalOrg" type="text" class="validate">
        <label for="iFiscalOrg">Identificaci&oacute;n Fiscal</label>
      </div>

      <div class="input-field col s6 ">
        <i class="material-icons prefix iconnegro ">business</i>
        <input disabled value="Tombola" id="nombreOrg" type="text" class="validate">
        <label for="nombreOrg">Nombre</label>
      </div>

      <div class="input-field col s6">
        <i class="material-icons prefix iconnegro">location_on</i>
        <input disabled value="Venezuela" id="paisOrg" type="text" class="validate">
        <label for="paisOrg">Pa&iacute;s</label>
      </div>


      <div class="input-field col s6">
        <i class="material-icons prefix iconnegro">phone</i>
        <input disabled value="0251-2336052" id="telefonoOrg" type="tel" class="validate">
        <label for="telefonoOrg">Tel&eacute;fono</label>
      </div>

      <div class="input-field col s6">
        <i class="material-icons prefix iconnegro">email</i>
        <input disabled value="tombola@gmail.com" id="emailAdmO" type="text" class="validate">
        <label for="emailAdmO">Email</label>
      </div>

      <div class="input-field col s6">
        <i class="material-icons prefix iconnegro">web</i>
        <input disabled value="www.tombola.com.ve" id="pagWeb" type="text" class="validate">
        <label for="pagWeb">Pagina Web</label>
      </div>

      <div class="input-field col s6">
        <i class="material-icons prefix iconnegro">web</i>
        <input disabled value="facebook.com/tombola" id="faceOrg" type="text" class="validate">
        <label for="faceOrg">Facebook</label>
      </div>

      <div class="input-field col s6">
        <i class="material-icons prefix iconnegro">web</i>
        <input disabled value="twitter.com/tombola" id="twitOrg" type="text" class="validate">
        <label for="twitOrg">Twitter</label>
      </div>

      <div class="input-field col s6">
        <i class="material-icons prefix iconnegro">web</i>
        <input disabled value="instagram.com/tombola" id="instaOrg" type="text" class="validate">
        <label for="instaOrg">Instagram</label>
      </div>



      <div class="file-field input-field col s6">
        <div class="btn black disabled">
          <span>Logo</span>
          <input type="file" multiple>
        </div>
        <div class="file-path-wrapper">
          <input disabled value="tombola.jpg" class="file-path validate" type="text" placeholder="Upload one or more files">
        </div>
      </div>



    </div>


    <div class="center col s12">
      <a class=" waves-effect btn center white-text waves-light" <%=  link_to "Atras", paginas_consultar_org_path, class: "white-text" %></a>

    </div>
  </div>
</div>


</div>

<script>
    $(document).ready(function() {
        $('select').material_select();
    });
    $('select').material_select('destroy');
</script>

</body>

app/views/paginas/consultar_reportes.html.erb
<body class="fondoform" xmlns="http://www.w3.org/1999/html">
<div class="container ">
  <div class="row ">
    <div class="col s12 ">
      <h4 class="black-text center">Reportes Generados</h4>

      <div class="col s12 white">
        <table class=" centered " >
          <thead>
          <tr>
            <th data-field="price">C&oacute;digo</th>
            <th data-field="price">Fecha</th>
            <th data-field="price">Criterio</th>
            <th data-field="price"></th>
          </tr>
          </thead>

          <tbody>
          <tr>
            <td><a class=" waves-effect center blue-text waves-light" <%=  link_to "001", paginas_consultar_detalle_estadistica_intereses_path, class: "white-text" %></a></td>
            <td>01 August, 2015</td>
            <td>Por Intereses</td>
            <td><td><a href="#hola" onmouseDown="alert('¿Desea eliminar el reporte?')" class="blue-text">Eliminar</a></td></td>
          </tr>

          <tr>
            <td>002</td>
            <td>04 September, 2015</td>
            <td>M&aacute;s destacados</td>
            <td><td><a href="#hola" onmouseDown="alert('¿Desea eliminar el reporte?')" class="blue-text">Eliminar</a></td></td>
          </tr>

          <tr>
            <td>003</td>
            <td>28 November, 2015</td>
            <td>Por Edad</td>
            <td><td><a href="#hola" onmouseDown="alert('¿Desea eliminar el reporte?')" class="blue-text">Eliminar</a></td></td>
          </tr>

          <tr>
            <td>004</td>
            <td>04 February, 2016</td>
            <td>Por Intereses</td>
            <td><td><a href="#hola" onmouseDown="alert('¿Desea eliminar el reporte?')" class="blue-text">Eliminar</a></td></td>
          </tr>

          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>





<div class="center">
  <a class=" waves-effect btn center white-text waves-light" <%=  link_to "Atras", paginas_opc_analista_org_path, class: "white-text" %></a>
</div>
</body>

app/views/paginas/habilitar_organizacion_administrador.html.erb
<body class="fondoform" xmlns="http://www.w3.org/1999/html">
<div class="container ">
  <div class="row ">
    <div class="col s12 ">
      <h4 class="black-text center">Habilitar Organizaci&oacute;n/Administrador</h4>

      <div class="col s12 white">
        <table class=" centered " >
          <thead>
          <tr>
            <th data-field="id">Organizaci&oacute;n</th>
            <th data-field="name">Administrador Asociado</th>
            <th data-field="price">Habilitar - Deshabilitar</th>
          </tr>
          </thead>

          <tbody>
          <tr>
            <td><a class=" waves-effect center blue-text waves-light" <%=  link_to "Tombola", paginas_consultar_detalle_org_path, class: "white-text" %></a></td>
            <td><a class=" waves-effect center blue-text waves-light" <%=  link_to "Mario Aguirre", paginas_consultar_detalle_org_path, class: "white-text" %></a></td>
            <td class="switch"><label>
              Off
              <input type="checkbox">
              <span class="lever"></span>
              On
            </label>
            </td>

          </tr>
          <tr>
            <td> <a href="#!" class=class="waves-effect">Cano</a></td>
            <td><a href="#!" class=class="waves-effect">Leonel Paleta</a></td>
            <td class="switch"><label>
              Off
              <input type="checkbox">
              <span class="lever"></span>
              On
            </label>
            </td>
          </tr>
          <tr>
            <td> <a href="#!" class="waves-effect">Facebook</a></td>
            <td><a href="#!" class="waves-effect">Mark Zuckerberg</a></td>
            <td class="switch"><label>
              Off
              <input type="checkbox">
              <span class="lever"></span>
              On
            </label>
            </td>
          </tr>
          <tr>
            <td> <a href="#!" class="waves-effect">Jazmin</a></td>
            <td><a href="#!" class="waves-effect">Zoraida Sequera</a></td>
            <td class="switch"><label>
              Off
              <input type="checkbox">
              <span class="lever"></span>
              On
            </label>
            </td>
          </tr>
          <tr>
            <td> <a href="#!" class="waves-effect">GMotors</a></td>
            <td><a href="#!" class="waves-effect">Jorge Rond&oacute;n</a></td>
            <td class="switch"><label>
              Off
              <input type="checkbox">
              <span class="lever"></span>
              On
            </label>
            </td>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>





<div class="center">
  <a class=" waves-effect btn center white-text waves-light"
     onmouseDown="alert('Los cambios se han realizado exitosamente')"  >Guardar</a>
  <a class=" waves-effect btn center white-text waves-light" <%=  link_to "Atras", paginas_opc_administrador_sistema_path, class: "white-text" %></a>

</div>
</body>

app/views/paginas/modificar_datos_admOrg.html.erb
<body class="fondoform">
<div class="container">
  <div class="row">

    <div class="col s12">
      <h4 class="black-text center">Modificar Datos</h4>
      <div class="input-field col s6">
        <input disabled value="Administrador de la Organizaci&oacute;n" id="disabled" type="text" class="validate">
        <label for="disabled">Rol </label>
      </div>

      <div class="input-field col s6 ">
        <i class="material-icons prefix iconnegro">account_circle</i>
        <input value="Mario" id="nombreAdmO" type="text" class="validate">
        <label for="nombreAdmO">Nombre</label>
      </div>

      <div class="input-field col s6 ">
        <i class="material-icons prefix iconnegro">account_circle</i>
        <input value="Aguirre" id="apellidoAdmO" type="text" class="validate">
        <label for="apellidoAdmO">Apellido</label>
      </div>

      <div class="input-field col s6">
        <i class="material-icons prefix iconnegro">email</i>
        <input value="maguirre@gmail.com" id="emailAdmO" type="text" class="validate">
        <label for="emailAdmO">Email</label>
      </div>

      <div class="input-field col s6">
        <i class="material-icons prefix iconnegro">phone</i>
        <input value="0276-8524798" id="telefonoAdmO" type="tel" class="validate">
        <label for="telefonoAdmO">Tel&eacute;fono</label>
      </div>


      <div class="input-field col s6">
        <select disabled>
          <option value disabled="2">Masculino</option>
        </select>
        <label>Sexo</label>
      </div>

      <div class=" input-field col s6">
        <input value="06 February, 1980" id="fechanacAdmO" type="date" class="datepicker">
      </div>

      <div class="file-field input-field col s6">
        <div class="btn black">
          <span>Foto</span>
          <input  type="file" multiple>
        </div>
        <div class="file-path-wrapper">
          <input class="file-path validate" type="text" placeholder="valen.jpg">
        </div>
      </div>


      <div class="center">
        <a onmouseDown="alert('Los cambios se realizaron de manera exitosa')"
           id="btnSiguienteRegAdmO" class="btn waves-effect waves-light" type="submit">Guardar</a>
        <a class=" waves-effect btn center white-text waves-light" <%=  link_to "Atras", paginas_opc_administrador_org_path, class: "white-text" %></a>
      </div>
    </div>
  </div>

</div>

<script>
    $(document).ready(function() {
        $('select').material_select();
    });
</script>

<script>
    $('.datepicker').pickadate({
        selectMonths: true, // Creates a dropdown to control month
        selectYears: 10, // Creates a dropdown of 15 years to control year
        currentText: 'Hoy',
        firstDay: 1,
        dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
        closeText: 'Cerrar'
    });

</script>


</body>

app/views/paginas/modificar_datos_analista_org.html.erb
<body class="fondoform" xmlns="http://www.w3.org/1999/html">
<div class="container">
  <div class="row">

    <div class="col s12">
      <h4 class="black-text center">Modificar Datos</h4>
      <div class="input-field col s6">
        <select disabled>
          <option value disabled="2">Analista</option>
        </select>
        <label>Rol</label>
      </div>

      <div class="input-field col s6 ">
        <i class="material-icons prefix iconnegro">account_circle</i>
        <input value="Jos&eacute;" id="nombreAn" type="text" class="validate">
        <label for="nombreAn">Nombre</label>
      </div>

      <div class="input-field col s6 ">
        <i class="material-icons prefix iconnegro">account_circle</i>
        <input value="Molina" id="apellidoAn" type="text" class="validate">
        <label for="apellidoAn">Apellido</label>
      </div>

      <div class="input-field col s6">
        <i class="material-icons prefix iconnegro">email</i>
        <input value="molina@gmail.com" id="emailAn" type="text" class="validate">
        <label for="emailAn">Email</label>
      </div>

      <div class="input-field col s6">
        <i class="material-icons prefix iconnegro">phone</i>
        <input value="0424-5748844" id="telefonoAn" type="tel" class="validate">
        <label for="telefonoAn">Tel&eacute;fono</label>
      </div>


      <div class="input-field col s6">
        <select disabled>

          <option value disabled="1">Masculino</option>
        </select>
        <label>Sexo</label>
      </div>

      <div class=" input-field col s6">
        <input value="23 May, 1986" id="fechanacAn" type="date" class="datepicker">
      </div>

      <div class="file-field input-field col s6">
        <div class="btn black">
          <span>Foto</span>
          <input type="file" multiple>
        </div>
        <div class="file-path-wrapper">
          <input class="file-path validate" type="text" placeholder="Upload one or more files">
        </div>
      </div>


      <div class="center">
        <a onmouseDown="alert('Los cambios se realizaron de manera exitosa')"
           id="btnSiguienteRegAdmO" class="btn waves-effect waves-light" type="submit">Guardar</a>
        <a class=" waves-effect btn center white-text waves-light" <%=  link_to "Atras", paginas_opc_analista_org_path, class: "white-text" %></a>
      </div>

    </div>
  </div>

</div>

<script>
    $(document).ready(function() {
        $('select').material_select();
    });
</script>

<script>
    $('.datepicker').pickadate({
        selectMonths: true, // Creates a dropdown to control month
        selectYears: 10, // Creates a dropdown of 15 years to control year
        currentText: 'Hoyejecutivo_sistema',
        firstDay: 1,
        dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
        closeText: 'Cerrar'
    });

</script>


</body>

app/views/paginas/modificar_org.html.erb
<body class="fondoform" xmlns="http://www.w3.org/1999/html">
<div class="container">
  <div class="row">


      <h4 class="black-text center">Modificar Datos de la Organizaci&oacute;n</h4>
    <div class="col s12 fondodiv">

      <div class="input-field col s6">
        <select disabled>
          <option value=""disabled selected>Oro</option>
          <option value="1">Bronce - Gratis</option>
          <option value="2">Plata - 50$</option>
          <option value="3">Oro - 200$</option>
        </select>
        <label>Tipo de plan</label>
      </div>

      <div class="input-field col s6">
        <select disabled>
          <option value="" disabled selected>Servicios</option>
          <option value="1">Producci&oacute;n</option>
          <option value="2">Compra - Venta</option>
          <option value="2">Servicios</option>
          <option value="3">Sin fines de Lucro</option>
        </select>
        <label>Tipo de Organizaci&oacute;n</label>
      </div>

      <div class="input-field col s6 ">
        <i class="material-icons prefix iconnegro">business</i>
        <input disabled value="2549856" id="iFiscalOrg" type="text" class="validate">
        <label  for="iFiscalOrg">Identificaci&oacute;n Fiscal</label>
      </div>

      <div class="input-field col s6 ">
        <i class="material-icons prefix iconnegro ">business</i>
        <input value="Tombola" id="nombreOrg" type="text" class="validate">
        <label class="active" for="nombreOrg">Nombre</label>
      </div>

      <div class="input-field col s6">
        <i class="material-icons prefix iconnegro">location_on</i>
        <input value="Venezuela"id="paisOrg" type="text" class="validate">
        <label class="active" for="paisOrg">Pa&iacute;s</label>
      </div>


      <div class="input-field col s6">
        <i class="material-icons prefix iconnegro">phone</i>
        <input value="0251-2336052"id="telefonoOrg" type="tel" class="validate">
        <label class="active" for="telefonoOrg">Tel&eacute;fono</label>
      </div>

      <div class="input-field col s6">
        <i class="material-icons prefix iconnegro">email</i>
        <input value="tombola@gmail.com" id="emailAdmO" type="text" class="validate">
        <label class="active"for="emailAdmO">Email</label>
      </div>

      <div class="input-field col s6">
        <i class="material-icons prefix iconnegro">web</i>
        <input value="www.tombola.com.ve" id="pagWeb" type="text" class="validate">
        <label class="active"for="pagWeb">Pagina Web</label>
      </div>

      <div class="input-field col s6">
        <i class="material-icons prefix iconnegro">web</i>
        <input value="facebook.com/tombola" id="faceOrg" type="text" class="validate">
        <label class="active"for="faceOrg">Facebook</label>
      </div>

      <div class="input-field col s6">
        <i class="material-icons prefix iconnegro">web</i>
        <input value="twitter.com/tombola" id="twitOrg" type="text" class="validate">
        <label class="active" for="twitOrg">Twitter</label>
      </div>

      <div class="input-field col s6">
        <i class="material-icons prefix iconnegro">web</i>
        <input value="instagram.com/tombola"id="instaOrg" type="text" class="validate">
        <label class="active" for="instaOrg">Instagram</label>
      </div>



      <div class="file-field input-field col s6">
        <div class="btn black">
          <span>Logo</span>
          <input type="file" multiple>
        </div>
        <div class="file-path-wrapper">
          <input value="tombola.jpg" class="file-path validate" type="text" placeholder="Upload one or more files">
        </div>
      </div>



    </div>

    <div class="row">
      <div class="center col s12">

        <a onmouseDown="alert('Los cambios se realizaron de manera exitosa')"
           id="btnSiguienteRegAdmO" class="btn waves-effect waves-light" type="submit">Guardar</a>
        <a class=" waves-effect btn center white-text waves-light" <%=  link_to "Atras", paginas_opc_administrador_org_path, class: "white-text" %></a>
      </div>
    </div>
  </div>
</div>

</div>

<script>
    $(document).ready(function() {
        $('select').material_select();
    });
</script>

<script>
    $('.datepicker').pickadate({
        selectMonths: true, // Creates a dropdown to control month
        selectYears: 10, // Creates a dropdown of 15 years to control year
        currentText: 'Hoy',
        firstDay: 1,
        dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
        closeText: 'Cerrar'
    });

</script>


</body>

app/views/paginas/opc_administrador_org.html.erb
<body class="fondoform">
<div class="container ">
  <div class="row ">
    <div class="col s12 ">
      <h4 class="black-text center">Administrador de la Organizaci&oacute;n</h4>

      <div class="nombrePerfil">
        <label class="black-text ">¡Hola! Mario Aguirre</label>
      </div>


      <img class="imgPerfil" src="<%= asset_path 'perfil.png' %>">

      <div class="col s4 white">
        <table class=" centered " >
          <thead>
          <tr>
            <th data-field="id">Opciones</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td> <a class=" blue-text" <%=  link_to "Registrar Empleados", paginas_registro_empleados_path, class: "white-text" %></a> </td>
          </tr>
          <tr>
            <td> <a class=" blue-text" <%=  link_to "Consultar Ejecutivos", paginas_consultar_ejecutivos_org_path, class: "white-text" %></a> </td>
          </tr>

          <tr>
            <td> <a class=" blue-text" <%=  link_to "Consultar Analistas", paginas_consultar_analistas_org_path, class: "white-text" %></a> </td>
          </tr>
          <tr>
            <td> <a class=" blue-text" <%=  link_to "Modificar Rol", paginas_modificar_rol_org_path, class: "white-text" %></a> </td>
          </tr>
          <tr>
            <td> <a class=" blue-text" <%=  link_to "Publicar novedad", paginas_publicar_novedad_path, class: "white-text" %></a> </td>
          </tr>
          <tr>
            <td> <a class=" blue-text" <%=  link_to "Consultar novedades", paginas_consultar_novedades_path, class: "white-text" %></a> </td>
          </tr>
          <tr>
            <td> <a class=" blue-text" <%=  link_to "Registrar Pagos", paginas_registro_pago_org_path, class: "white-text" %></a> </td>
          </tr>
          <tr>
            <td> <a class=" blue-text" <%=  link_to "Consultar Pagos", paginas_consultar_pagos_org_path, class: "white-text" %></a> </td>
          </tr>
          <tr>
            <td> <a class=" blue-text" <%=  link_to "Modificar Datos de la Organización", paginas_modificar_org_path, class: "white-text" %></a> </td>
          </tr>
          <tr>
            <td> <a class=" blue-text" <%=  link_to "Modificar Datos", paginas_modificar_datos_admOrg_path, class: "white-text" %></a> </td>
          </tr>
          <tr>
            <td> <a class=" blue-text" <%=  link_to "Cambiar fondo", paginas_cambiar_fondo_path, class: "white-text" %></a> </td>
          </tr>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>

app/views/paginas/publicar_campanna_sistema.html.erb
<body class="fondoform">
<div class="section row container" id="contactanos">

  <div class="row">
    <h4 class="black-text center">Publicar Campaña de Crumbik</h4>
  </div>

  <div class=" input-field col s7">
    <input id="fechaCampSist" type="date" class="datepicker">
    <label for="fechaCampSist">Fecha</label>
  </div>

  <div class="row ">
    <form>
      <div class="input-field col s7 ">
        <i class="material-icons prefix iconnegro">spellcheck</i>
        <input id="asuntoCampSist" type="text" class="validate">
        <label for="asuntoCampSist">Asunto</label>
      </div>

      <div class="input-field col s7 ">
        <i class="material-icons prefix iconnegro">mode_edit</i>
        <textarea id="mensajeCampSist" class="materialize-textarea"></textarea>
        <label for="mensajeCampSist">Mensaje </label>
      </div>
    </form>
  </div>

  <div class="file-field input-field col s7">
    <div class="btn black">
      <span>Archivo</span>
      <input type="file" multiple>
    </div>
    <div class="file-path-wrapper">
      <input class="file-path validate" type="text" placeholder="Upload one or more files">
    </div>
  </div>

  <div class="row" >
    <div class="col s12 center" >
      <button class="btn waves-effect waves-light offset-s4" type="submit" name="action">Publicar</button>
      <a class=" waves-effect btn center white-text waves-light" <%=  link_to "Atras", paginas_opc_ejecutivo_sistema_path, class: "white-text" %></a>
    </div>
  </div>


</div>
<script>
    $('.datepicker').pickadate({
        selectMonths: true, // Creates a dropdown to control month
        selectYears: 10, // Creates a dropdown of 15 years to control year
        currentText: 'Hoy',
        firstDay: 1,
        dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
        closeText: 'Cerrar'
    });

</script>
</body>

app/views/paginas/registro_reporte.html.erb
<body class="fondoform" xmlns="http://www.w3.org/1999/html">
<div class="container">
  <div class="row">

    <div class="col s12 ">
      <h4 class="black-text center">Generar Reporte por Campaña</h4>

      <div class="input-field col s6 ">
        <select>
          <option value=""disabled selected>Seleccione una opcion</option>
          <option value="1">Por Intereses</option>
          <option value="2">Mas destacados redes sociales (Facebook)</option>
          <option value="3">Por edad</option>
        </select>
        <label>Criterio para el Reporte</label>
      </div>


      <div class="row">
        <div class="center col s12">

          <a class=" waves-effect btn center white-text waves-light" <%=  link_to "Generar", paginas_detalle_estadistica_interes_path, class: "white-text" %></a>
          <a class=" waves-effect btn center white-text waves-light" <%=  link_to "Atras", paginas_opc_analista_org_path, class: "white-text" %></a>
        </div>
      </div>






    </div>
  </div>

</div>

<script>
    $(document).ready(function() {
        $('select').material_select();
    });
    $('select').material_select('destroy');
</script>

</body>