config/routes.rb
Rails.application.routes.draw do

  resources :functions
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :profiles
  resources :events
  resources :menu_options
  resources :rols
  resources :countries
  resources :interactions
  resources :advertising_campaigns
  resources :products
  resources :payments
  get 'welcome/index'

  resources :organizations

  devise_for :users, :controllers => { :registration => "registration", :omniauth_callbacks => "omniauth_callbacks" }
  scope "/admin" do
    resources :users
  end
  get 'functions/sidebar' => 'functions#sidebar'

  devise_scope :user do
     get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
     get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end

   root 'paginas#index'

      get 'paginas/formulario'
      get 'paginas/registroAdministradorOrg'
      get 'paginas/iniciarSesionAdmOrg'
      get 'paginas/registro_org'
      get 'paginas/consultar_org'
      get 'paginas/consultar_detalle_org'
      get 'paginas/modificar_org'
      get 'paginas/opc_administrador_sistema'
      get 'paginas/habilitar_organizacion_administrador'
      get 'paginas/consultar_detalle_adm'
      get 'paginas/registro_pago'
      get 'paginas/consultar_pagos'
      get 'paginas/modificar_datos_admS'
      get 'paginas/registro_ejecutivoS'
      get 'paginas/consultar_ejecutivos'
      get 'paginas/opc_administrador_org'
      get 'paginas/registro_empleados'
      get 'paginas/consultar_ejecutivos_org'
      get 'paginas/consultar_analistas_org'
      get 'paginas/registro_pago_org'
      get 'paginas/consultar_pagos_org'
      get 'paginas/modificar_rol_org'
      get 'paginas/modificar_datos_admOrg'
      get 'paginas/publicar_novedad'
      get 'paginas/cambiar_fondo'
      get 'paginas/opc_ejecutivo_org'
      get 'paginas/publicar_campanna'
      get 'paginas/consultar_campannas'
      get 'paginas/modificar_datos_ejecutivo_org'
      get 'paginas/registro_evento_ejecutivo_org'
      get 'paginas/consultar_novedades'
      get 'paginas/consultar_eventos_ejecutivo'
      get 'paginas/publicar_campanna_sistema'
      get 'paginas/consultar_campannas_sistema'
      get 'paginas/modificar_datos_ejecutivo_sistema'
      get 'paginas/opc_ejecutivo_sistema'
      get 'paginas/opc_analista_org'
      get 'paginas/modificar_datos_analista_org'
      get 'paginas/registro_reporte'
      get 'paginas/consultar_reportes'
      get 'paginas/iniciar_sesion_cliente'
      get 'paginas/registro_cliente'
      get 'paginas/registro_org_administrador_sistema'
      get 'paginas/registro_administradorOrg_admSist'
      get 'paginas/opc_cliente'
      get 'paginas/detalle_estadistica_interes'
      get 'paginas/consultar_detalle_estadistica_intereses'
      get 'paginas/modificar_datos_cliente'
      get 'paginas/cambiar_fondo_cliente'

   get ':controller(/:action(/:id))(.:format)'
   post ':controller(/:action(/:id))(.:format)'
end

app/models/menu_option.rb
class MenuOption < ActiveRecord::Base
  has_and_belongs_to_many :rols
end

app/controllers/menu_options_controller.rb
class MenuOptionsController < ApplicationController
  before_action :set_menu_option, only: [:show, :edit, :update, :destroy]

  # GET /menu_options
  # GET /menu_options.json
  def index
    @menu_options = MenuOption.all
  end

  # GET /menu_options/1
  # GET /menu_options/1.json
  def show
  end

  # GET /menu_options/new
  def new
    @menu_option = MenuOption.new
  end

  # GET /menu_options/1/edit
  def edit
  end

  # POST /menu_options
  # POST /menu_options.json
  def create
    @menu_option = MenuOption.new(menu_option_params)

    respond_to do |format|
      if @menu_option.save
        format.html { redirect_to @menu_option, notice: 'Menu option was successfully created.' }
        format.json { render :show, status: :created, location: @menu_option }
      else
        format.html { render :new }
        format.json { render json: @menu_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_options/1
  # PATCH/PUT /menu_options/1.json
  def update
    respond_to do |format|
      if @menu_option.update(menu_option_params)
        format.html { redirect_to @menu_option, notice: 'Menu option was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu_option }
      else
        format.html { render :edit }
        format.json { render json: @menu_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_options/1
  # DELETE /menu_options/1.json
  def destroy
    @menu_option.destroy
    respond_to do |format|
      format.html { redirect_to menu_options_url, notice: 'Menu option was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_option
      @menu_option = MenuOption.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_option_params
      params.require(:menu_option).permit(:name)
    end
end

app/helpers/menu_options_helper.rb
module MenuOptionsHelper
end

app/views/menu_options/_form.html.erb
<%= form_for(@menu_option) do |f| %>
  <% if @menu_option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu_option.errors.count, "error") %> prohibited this menu_option from being saved:</h2>

      <ul>
      <% @menu_option.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menu_options/edit.html.erb
<h1>Editing Menu Option</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu_option %> |
<%= link_to 'Back', menu_options_path %>

app/views/menu_options/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Menu Options</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menu_options.each do |menu_option| %>
      <tr>
        <td><%= menu_option.name %></td>
        <td><%= link_to 'Show', menu_option %></td>
        <td><%= link_to 'Edit', edit_menu_option_path(menu_option) %></td>
        <td><%= link_to 'Destroy', menu_option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu option', new_menu_option_path %>

app/views/menu_options/new.html.erb
<h1>New Menu Option</h1>

<%= render 'form' %>

<%= link_to 'Back', menu_options_path %>

app/views/menu_options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @menu_option.name %>
</p>

<%= link_to 'Edit', edit_menu_option_path(@menu_option) %> |
<%= link_to 'Back', menu_options_path %>