config/routes.rb
Rails.application.routes.draw do

  resources :functions
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :profiles
  resources :events
  resources :menu_options
  resources :rols
  resources :countries
  resources :interactions
  resources :advertising_campaigns
  resources :products
  resources :payments
  get 'welcome/index'

  resources :organizations

  devise_for :users, :controllers => { :registration => "registration", :omniauth_callbacks => "omniauth_callbacks" }
  scope "/admin" do
    resources :users
  end
  get 'functions/sidebar' => 'functions#sidebar'

  devise_scope :user do
     get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
     get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end

   root 'paginas#index'

      get 'paginas/formulario'
      get 'paginas/registroAdministradorOrg'
      get 'paginas/iniciarSesionAdmOrg'
      get 'paginas/registro_org'
      get 'paginas/consultar_org'
      get 'paginas/consultar_detalle_org'
      get 'paginas/modificar_org'
      get 'paginas/opc_administrador_sistema'
      get 'paginas/habilitar_organizacion_administrador'
      get 'paginas/consultar_detalle_adm'
      get 'paginas/registro_pago'
      get 'paginas/consultar_pagos'
      get 'paginas/modificar_datos_admS'
      get 'paginas/registro_ejecutivoS'
      get 'paginas/consultar_ejecutivos'
      get 'paginas/opc_administrador_org'
      get 'paginas/registro_empleados'
      get 'paginas/consultar_ejecutivos_org'
      get 'paginas/consultar_analistas_org'
      get 'paginas/registro_pago_org'
      get 'paginas/consultar_pagos_org'
      get 'paginas/modificar_rol_org'
      get 'paginas/modificar_datos_admOrg'
      get 'paginas/publicar_novedad'
      get 'paginas/cambiar_fondo'
      get 'paginas/opc_ejecutivo_org'
      get 'paginas/publicar_campanna'
      get 'paginas/consultar_campannas'
      get 'paginas/modificar_datos_ejecutivo_org'
      get 'paginas/registro_evento_ejecutivo_org'
      get 'paginas/consultar_novedades'
      get 'paginas/consultar_eventos_ejecutivo'
      get 'paginas/publicar_campanna_sistema'
      get 'paginas/consultar_campannas_sistema'
      get 'paginas/modificar_datos_ejecutivo_sistema'
      get 'paginas/opc_ejecutivo_sistema'
      get 'paginas/opc_analista_org'
      get 'paginas/modificar_datos_analista_org'
      get 'paginas/registro_reporte'
      get 'paginas/consultar_reportes'
      get 'paginas/iniciar_sesion_cliente'
      get 'paginas/registro_cliente'
      get 'paginas/registro_org_administrador_sistema'
      get 'paginas/registro_administradorOrg_admSist'
      get 'paginas/opc_cliente'
      get 'paginas/detalle_estadistica_interes'
      get 'paginas/consultar_detalle_estadistica_intereses'
      get 'paginas/modificar_datos_cliente'
      get 'paginas/cambiar_fondo_cliente'

   get ':controller(/:action(/:id))(.:format)'
   post ':controller(/:action(/:id))(.:format)'
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  belongs_to :country
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  after_create :create_tenant

  def create_tenant
    Apartment::Tenant.create(name)
  end


end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /organizacions
  # GET /organizacions.json
  def index
    @organizations = Organization.all
  end

  # GET /organizacions/1
  # GET /organizacions/1.json
  def show
  end

  # GET /organizacions/new
  def new
    @organization= Organization.new
  end

  # GET /organizacions/1/edit
  def edit
  end

  # POST /organizacions
  # POST /organizacions.json
  def create
    @organization = Organization.new(organization_params)

    @link = @organization.name+'.lvh.me:3000/users/sign_up'
    puts @link
    respond_to do |format|
      if @organization.save
        format.html { redirect_to "http://"+@organization.name+".lvh.me:3000/users/sign_up" , notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizacions/1
  # PATCH/PUT /organizacions/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organizacion was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizacions/1
  # DELETE /organizacions/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organizacion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_organization
    @organization = Organizacion.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def organization_params
    params.require(:organization).permit(:name, :email, :slogan, :mission, :vision, :phone, :avatar)
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<div class="container">
  <div class="row">
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col s6">
    <%= f.label :Nombre, class: 'black-text'%><br>
    <%= f.text_field :name %>
  </div>
  <div class="field col s6">
    <%= f.label :Email, class: 'black-text' %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field col s6 ">
    <%= f.label :Eslogan, class: 'black-text' %><br>
    <%= f.text_area :slogan %>
  </div>
  <div class="field col s6">
    <%= f.label :Mision, class: 'black-text' %><br>
    <%= f.text_area :mission %>
  </div>
  <div class="field col s6">
    <%= f.label :Vision, class: 'black-text' %><br>
    <%= f.text_area :vision %>
  </div>
  <div class="field col s6">
    <%= f.label :Telefono, class: 'black-text' %><br>
    <%= f.text_field :phone %>
  </div>
        <div class="field col s9">
          <%= f.label :Logo, class: 'black-text' %><br>

          <%= f.file_field :avatar,  :onchange => 'readURL(this)'%>


        </div>



        <div class="actions row ">
          <div class="col s12 center">
            <%= f.submit "Registrar" , class: 'waves-effect waves-light btn ' %>
          </div>
        </div>

        <div style="margin-left: 800px; margin-top: -438px;">
          <img id="img_prev"/>
        </div>

<% end %>
  </div>
</div>

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#img_prev')
                        .attr('src', e.target.result)
                        .width(250)
                        .height(250);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<div class="col s12 m12">
<div class="container">


<p id="notice"><%= notice %></p>


<h2 class="center">Organizaciones Registradas</h2>

<table class="centered striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Email</th>
      <th>Eslogan</th>
      <th>Misi&oacute;n</th>
      <th>Visi&oacute;n</th>
      <th>Telefono</th>
      <th>Logo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.email %></td>
        <td><%= organization.slogan %></td>
        <td><%= organization.mission %></td>
        <td><%= organization.vision %></td>
        <td><%= organization.phone %></td>
        <td><%= image_tag(organization.avatar, :width => 50) %></td>
        <td><%= link_to 'Consultar', organization %></td>
        <td><%= link_to 'Modificar', edit_organization_path(organization) %></td>
        <td><%= link_to 'Eliminar', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="col s12 center-align">
  <a class="btn waves-effect waves-light" <%= link_to 'Registrar Organizacion', new_organization_path %></a>
</div>
</div>
</div>

app/views/organizations/new.html.erb
<h2 class="center-align">Registro de Organizaci&oacute;n</h2>

<%= render 'form' %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @organization.email %>
</p>

<p>
  <strong>Slogan:</strong>
  <%= @organization.slogan %>
</p>

<p>
  <strong>Mission:</strong>
  <%= @organization.mission %>
</p>

<p>
  <strong>Vision:</strong>
  <%= @organization.vision %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @organization.phone %>
</p>

<p>
  <strong>Status:</strong>
  <%= @organization.status %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>